services:
  db:
    image: mariadb:10.8
    container_name: ${MARIADB_CONTAINER_NAME:-mariadb_container}
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./data/mariadb:/var/lib/mysql

    networks:
      - shared-phpmyadmin

networks:
  shared-phpmyadmin:
    external: true
    name: net-phpmyadmin_shared
