services:
  db:
    image: mariadb:10.8
    container_name: ${MARIADB_CONTAINER_NAME:-mariadb_container}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DEFAULT_DATABASE}
      MARIADB_USER: ${MARIADB_DEFAULT_USER}
      MARIADB_PASSWORD: ${MARIADB_DEFAULT_PASSWORD}

    volumes:
      - ./data/mariadb:/var/lib/mysql

    networks:
      - shared-phpmyadmin

networks:
  shared-phpmyadmin:
    external: true
    name: net-phpmyadmin_shared
